### ISSUE TITLE
Empty whitelist

### ISSUE THREAD

**Issue by wizrds** [mikekonan/freqtrade-proxy#16]
**Freqtrade Version:** 2021.10
**Proxy Version:** I was unable to find the version for the specific docker image on my machine, however this is the digest: _"mikekonan/freqtrade-proxy@sha256:89639a81424877576624d108bfc5cd4a818ff42b5b285487151a455379a61996"_
**Operating System:** Ubuntu 20.04

Here is my current exchange information in my configuration:
```
"name": "kucoin",
        "key": "",
        "secret": "",
        "password": "",
        "ccxt_config": {
            "enableRateLimit": false,
            "timeout": 60000,
            "urls": {
                "api": {
                    "public": "http://freqtrade-proxy:8080/kucoin",
                    "private": "http://freqtrade-proxy:8080/kucoin"
                }
            }
        },
        "ccxt_async_config": {
            "enableRateLimit": false,
            "timeout": 60000
        },
```

My filters:
```        
{
            "method": "VolumePairList",
            "number_assets": 80,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {"method": "AgeFilter", "min_days_listed": 7},
        {"method": "SpreadFilter", "max_spread_ratio": 0.006},
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 3,
            "min_rate_of_change": 0.05,
            "refresh_period": 1800
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 3,
            "min_volatility": 0.02,
            "max_volatility": 0.75,
            "refresh_period": 43200
        },
        {"method": "ShuffleFilter"}
```

On start, the proxy works perfectly. After a certain amount of time, my whitelist is down to a very small amount of pairs. Usually 1-6. How it happens, or how long it takes I'm not sure. I have tried pulling the newest image from docker hub, however it doesn't seem to have solved my issue. Sometime within 24 hours of starting this happens. The output of my whitelist is as follows when the problem arises:
```
Using whitelist ['VolumePairList', 'AgeFilter', 'SpreadFilter', 'RangeStabilityFilter', 'VolatilityFilter', 'ShuffleFilter'] with 6 pairs
SUKU/USDT, ENS/USDT, TRX/USDT, OPCT/USDT, LYXE/USDT, WILD/USDT
```

**Comment by mikekonan** [comment]
Ensure you are using latest version.

https://hub.docker.com/r/mikekonan/freqtrade-proxy/tags

**Comment by wizrds** [comment]
I've pruned the images and pulled new ones several times. Still occurs.

**Comment by mikekonan** [comment]
Could you show the output of "docker images" and freqtrade logs?

**Comment by swelbyboy** [comment]
logs before it happened ---


2021-11-26 16:16:29,509 - RangeStabilityFilter - INFO - Removed BTC/USDT from whitelist, because rate of change over 5 days is 6.630, which is above the threshold of 1.25.
2021-11-26 16:16:29,510 - RangeStabilityFilter - INFO - Removed ETH/USDT from whitelist, because rate of change over 5 days is 20.155, which is above the threshold of 1.25.
2021-11-26 16:16:29,511 - RangeStabilityFilter - INFO - Removed SAND/USDT from whitelist, because rate of change over 5 days is 1.266, which is above the threshold of 1.25.
2021-11-26 16:16:29,512 - RangeStabilityFilter - INFO - Removed SHIB/USDT from whitelist, because rate of change over 5 days is 19.662, which is above the threshold of 1.25.
2021-11-26 16:16:29,512 - RangeStabilityFilter - INFO - Removed GALAX/USDT from whitelist, because rate of change over 5 days is 2.393, which is above the threshold of 1.25.
2021-11-26 16:16:29,513 - RangeStabilityFilter - INFO - Removed LUNA/USDT from whitelist, because rate of change over 5 days is 252.921, which is above the threshold of 1.25.
2021-11-26 16:16:29,513 - RangeStabilityFilter - INFO - Removed MANA/USDT from whitelist, because rate of change over 5 days is 14.913, which is above the threshold of 1.25.
2021-11-26 16:16:29,514 - RangeStabilityFilter - INFO - Removed CRO/USDT from whitelist, because rate of change over 5 days is 37.462, which is above the threshold of 1.25.
2021-11-26 16:16:29,515 - RangeStabilityFilter - INFO - Removed KDA/USDT from whitelist, because rate of change over 5 days is 282.871, which is above the threshold of 1.25.
2021-11-26 16:16:29,515 - RangeStabilityFilter - INFO - Removed XRP/USDT from whitelist, because rate of change over 5 days is 10.382, which is above the threshold of 1.25.
2021-11-26 16:16:29,516 - RangeStabilityFilter - INFO - Removed AVAX/USDT from whitelist, because rate of change over 5 days is 14.750, which is above the threshold of 1.25.
2021-11-26 16:16:29,517 - RangeStabilityFilter - INFO - Removed REQ/USDT from whitelist, because rate of change over 5 days is 3.822, which is above the threshold of 1.25.
2021-11-26 16:16:29,517 - RangeStabilityFilter - INFO - Removed FTM/USDT from whitelist, because rate of change over 5 days is 21.804, which is above the threshold of 1.25.
2021-11-26 16:16:29,518 - RangeStabilityFilter - INFO - Removed KCS/USDT from whitelist, because rate of change over 5 days is 41.255, which is above the threshold of 1.25.
2021-11-26 16:16:29,518 - RangeStabilityFilter - INFO - Removed BNB/USDT from whitelist, because rate of change over 5 days is 40.727, which is above the threshold of 1.25.
2021-11-26 16:16:29,519 - RangeStabilityFilter - INFO - Removed VRA/USDT from whitelist, because rate of change over 5 days is 263.854, which is above the threshold of 1.25.
2021-11-26 16:16:29,520 - RangeStabilityFilter - INFO - Removed DOT/USDT from whitelist, because rate of change over 5 days is 26.548, which is above the threshold of 1.25.
2021-11-26 16:16:29,520 - RangeStabilityFilter - INFO - Removed LRC/USDT from whitelist, because rate of change over 5 days is 21.183, which is above the threshold of 1.25.
2021-11-26 16:16:29,521 - RangeStabilityFilter - INFO - Removed SOL/USDT from whitelist, because rate of change over 5 days is 9.392, which is above the threshold of 1.25.
2021-11-26 16:16:29,521 - RangeStabilityFilter - INFO - Removed ADA/USDT from whitelist, because rate of change over 5 days is 40.082, which is above the threshold of 1.25.
2021-11-26 16:16:29,522 - RangeStabilityFilter - INFO - Removed PYR/USDT from whitelist, because rate of change over 5 days is 26.837, which is above the threshold of 1.25.
2021-11-26 16:16:29,522 - RangeStabilityFilter - INFO - Removed LTC/USDT from whitelist, because rate of change over 5 days is 9.098, which is above the threshold of 1.25.
2021-11-26 16:16:29,523 - RangeStabilityFilter - INFO - Removed MATIC/USDT from whitelist, because rate of change over 5 days is 3.669, which is above the threshold of 1.25.
2021-11-26 16:16:29,523 - RangeStabilityFilter - INFO - Removed ROSE/USDT from whitelist, because rate of change over 5 days is 13.734, which is above the threshold of 1.25.
2021-11-26 16:16:29,524 - RangeStabilityFilter - INFO - Removed CRV/USDT from whitelist, because rate of change over 5 days is 5.058, which is above the threshold of 1.25.
2021-11-26 16:16:29,524 - RangeStabilityFilter - INFO - Removed RNDR/USDT from whitelist, because rate of change over 5 days is 24.143, which is above the threshold of 1.25.
2021-11-26 16:16:29,525 - RangeStabilityFilter - INFO - Removed BAT/USDT from whitelist, because rate of change over 5 days is 3.834, which is above the threshold of 1.25.
2021-11-26 16:16:29,526 - RangeStabilityFilter - INFO - Removed VET/USDT from whitelist, because rate of change over 5 days is 32.583, which is above the threshold of 1.25.
2021-11-26 16:16:29,526 - RangeStabilityFilter - INFO - Removed ENJ/USDT from whitelist, because rate of change over 5 days is 5.585, which is above the threshold of 1.25.
2021-11-26 16:16:29,527 - RangeStabilityFilter - INFO - Removed ATOM/USDT from whitelist, because rate of change over 5 days is 13.493, which is above the threshold of 1.25.
2021-11-26 16:16:29,527 - RangeStabilityFilter - INFO - Removed DOGE/USDT from whitelist, because rate of change over 5 days is 16.854, which is above the threshold of 1.25.
2021-11-26 16:16:29,528 - RangeStabilityFilter - INFO - Removed ONE/USDT from whitelist, because rate of change over 5 days is 610.894, which is above the threshold of 1.25.
2021-11-26 16:16:29,529 - RangeStabilityFilter - INFO - Removed LINK/USDT from whitelist, because rate of change over 5 days is 6.250, which is above the threshold of 1.25.
2021-11-26 16:16:29,529 - RangeStabilityFilter - INFO - Removed UOS/USDT from whitelist, because rate of change over 5 days is 31.006, which is above the threshold of 1.25.
2021-11-26 16:16:29,530 - RangeStabilityFilter - INFO - Removed QRDO/USDT from whitelist, because rate of change over 5 days is 39.000, which is above the threshold of 1.25.
2021-11-26 16:16:29,530 - RangeStabilityFilter - INFO - Removed ANKR/USDT from whitelist, because rate of change over 5 days is 4191.872, which is above the threshold of 1.25.
2021-11-26 16:16:29,531 - RangeStabilityFilter - INFO - Removed ZEC/USDT from whitelist, because rate of change over 5 days is 6.909, which is above the threshold of 1.25.
2021-11-26 16:16:29,531 - RangeStabilityFilter - INFO - Removed HTR/USDT from whitelist, because rate of change over 5 days is 21.095, which is above the threshold of 1.25.
2021-11-26 16:16:29,532 - RangeStabilityFilter - INFO - Removed ALGO/USDT from whitelist, because rate of change over 5 days is 12.465, which is above the threshold of 1.25.
2021-11-26 16:16:29,533 - RangeStabilityFilter - INFO - Removed MASK/USDT from whitelist, because rate of change over 5 days is 9999.000, which is above the threshold of 1.25.
2021-11-26 16:16:29,533 - RangeStabilityFilter - INFO - Removed RFOX/USDT from whitelist, because rate of change over 5 days is 15.966, which is above the threshold of 1.25.
2021-11-26 16:16:29,534 - RangeStabilityFilter - INFO - Removed XLM/USDT from whitelist, because rate of change over 5 days is 10.990, which is above the threshold of 1.25.
2021-11-26 16:16:29,534 - RangeStabilityFilter - INFO - Removed ELON/USDT from whitelist, because rate of change over 5 days is 62.571, which is above the threshold of 1.25.
2021-11-26 16:16:29,535 - RangeStabilityFilter - INFO - Removed TRX/USDT from whitelist, because rate of change over 5 days is 10.215, which is above the threshold of 1.25.
2021-11-26 16:16:29,536 - RangeStabilityFilter - INFO - Removed GRT/USDT from whitelist, because rate of change over 5 days is 21.169, which is above the threshold of 1.25.
2021-11-26 16:16:29,536 - RangeStabilityFilter - INFO - Removed LPT/USDT from whitelist, because rate of change over 5 days is 8.491, which is above the threshold of 1.25.
2021-11-26 16:16:29,537 - RangeStabilityFilter - INFO - Removed DYDX/USDT from whitelist, because rate of change over 5 days is 2.062, which is above the threshold of 1.25.
2021-11-26 16:16:29,537 - RangeStabilityFilter - INFO - Removed MOVR/USDT from whitelist, because rate of change over 5 days is 100.000, which is above the threshold of 1.25.
2021-11-26 16:16:29,538 - RangeStabilityFilter - INFO - Removed ICP/USDT from whitelist, because rate of change over 5 days is 31.974, which is above the threshold of 1.25.
2021-11-26 16:16:29,538 - RangeStabilityFilter - INFO - Removed SLP/USDT from whitelist, because rate of change over 5 days is 3.232, which is above the threshold of 1.25.
2021-11-26 16:16:29,604 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2021-11-26 16:16:34,509 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2021-11-26 16:16:39,510 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2021-11-26 16:16:44,514 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2021-11-26 16:16:49,518 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.

**Comment by swelbyboy** [comment]
![Screenshot 2021-11-26 at 16 41 05](https://user-images.githubusercontent.com/33932259/143611028-092ac72b-5143-4bd1-8689-57f3712fade6.png)

**Comment by swelbyboy** [comment]
I think it may just be my rate of change is too strict!?

**Comment by swelbyboy** [comment]
Is this calculating correctly? BTC hasn't got a rate of change of 6 over past 5 days

**Comment by Bloodhunter4rc** [comment]
should probably be fixed with https://github.com/freqtrade/freqtrade/commit/409a80176320a7d934eb5159faf35cb2a1ae9989 once its deployed

**Comment by b2pb** [comment]
Problem is w/ FT and not the proxy... See https://github.com/freqtrade/freqtrade/issues/5978, fixed in https://github.com/freqtrade/freqtrade/commit/409a80176320a7d934eb5159faf35cb2a1ae9989

**Comment by Bloodhunter4rc** [comment]
> Problem is w/ FT and not the proxy... See [freqtrade/freqtrade#5978](https://github.com/freqtrade/freqtrade/issues/5978), fixed in [freqtrade/freqtrade@409a801](https://github.com/freqtrade/freqtrade/commit/409a80176320a7d934eb5159faf35cb2a1ae9989)

the original issue by wizrds is not related to that as he is not using max rate of change, the one from welbyboy however is related to that...

**Comment by wizrds** [comment]
I can confirm that upgrading to the newest development tag of FT did not solve the issue

**Comment by mikekonan** [comment]
Could you provide your config?

**Comment by mikekonan** [comment]
Closing due no response
